feature_list: featuresets/featuresets24/v24_3_0/featurenames_selected.json
data: scraping/data/training_data.pckl
version: v24_3_1
outpath: models/models24/
model_names:
  - Gaussian_Naive_Bayes
  - Neural_Network
  - Logistic_Regression
  - Linear_SVC
  - KNN
  - Gaussian_RBF
  - Decision_Tree
  - Random_Forest
  - Adaboost