feature_list: featuresets/featuresets25/v25_2_0/featurenames_selected.json
data: scraping/data/training_data.pckl
version: v25_3_2
outpath: models/models25/
tuning: true
scoring: accuracy
feature_analysis: false
model_names:
  #- Gaussian_Naive_Bayes
  - Neural_Network
  - Logistic_Regression
  - Linear_SVC
  #- KNN
  #- Gaussian_RBF
  #- Decision_Tree
  - Random_Forest
  - Adaboost
  - GradientBoost
  - KernelSVM
meta_models:
  - Neural_Network
  #- Logistic_Regression
  #- Random Forest
  #- Adaboost
  #- GradientBoost
model_stacks:
  - all
  #- top5_accuracy
  #- top5_auc