feature_list: featuresets/featuresets25/v25_1_0/featurenames_selected.json
data: scraping/data/training_data.pckl
version: v25_1_0
outpath: models/models25/
tuning: true
feature_analysis: true
model_names:
  - Gaussian_Naive_Bayes
  - Neural_Network
  - Logistic_Regression
  - Linear_SVC
  - KNN
  - Gaussian_RBF
  - Decision_Tree
  - Random_Forest
  - Adaboost
  - GradientBoost
  - KernelSVM